/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yoon_scanner_ndk_Util */

#ifndef _Included_com_yoon_scanner_ndk_Util
#define _Included_com_yoon_scanner_ndk_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yoon_scanner_ndk_Util
 * Method:    warp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yoon_scanner_ndk_Util_warp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
